### ISSUE TITLE
Occasionally failed for OpenSSL with Nginx

### ISSUE THREAD

**Issue by jiavictor** [intel/QAT_Engine#50]
I am testing QucikAssist with Nginx.

I install upstream driver and QAT Engine.
Followed the README file patched and compiled Nginx.
Configed OpenSSL.

When testing with curl and ab, there were occasionally failed.

In the README file there is "Known Issue", but I don't think this belongs to.

You can refer to attachment for detail of the error or configuration of Nginx and OpenSSL.

Thanks.

[curl_error](https://user-images.githubusercontent.com/6112653/34090872-0823a260-e3f5-11e7-8a1c-ff4f9e984435.png)
[nginx_error.log](https://github.com/intel/QAT_Engine/files/1566684/nginx_error.log)
[nginx.conf.txt](https://github.com/intel/QAT_Engine/files/1566692/nginx.conf.txt)
[openssl.cnf.txt](https://github.com/intel/QAT_Engine/files/1566693/openssl.cnf.txt)

**Comment by stevelinsell** [comment]
Hi, @jiavictor,

The errors you are seeing appear to indicate that the QAT Engine is failing in the engine init stage, when making a call to the Quickassist API function icp_sal_userStartMulti().
If your problem is intermittent (i.e. most of the time requests are not failing) then it could be an issue to do with the NumProcesses section in the driver config file.
Do the issues occur after nginx processes are restarted? 
As before is there anything in the kernel log if you do a dmesg that is related to qat?
The config files you have sent appear to show a system that should be working ok, I couldn't spot anything suspicious in the files at first glance.
When configuring the NumProcesses parameter you need to allow additional processes to:
a) Take care of the master process as well as the child processes as the master process also needs a qat instance.
b) When restarting nginx processes the old ones may linger while the connections complete but the new  processes may start straight away. You need NumProcesses set high enough to account for these extra processes.

Kind Regards,

Steve.

**Comment by jiavictor** [comment]
Hi @stevelinsell 
I increased NumProcesses to 32 and the work process for Nginx is 10.
There is still failed.

With curl, the access is OK.
But with Apache ab, even -n 20 -c 10 still has some failure both in sync and async modes.
There were some "device qat_dev0 is busy" messages in dmesg.

I really want to know how to get rid of this.

Thanks.

**Comment by jiavictor** [comment]
Hi @stevelinsell 

I disabled SELinux and everything goes fine.
But the performance of using QAT has almost no different when using CPU.
In the report from INTEL, there is significant high concurrency when using QAT.

So may I have the configuration advice on how to get the high concurrency on QAT, Nginx and OpenSSL?

**Comment by stevelinsell** [comment]
Closing as disabling SELinux resolved the issue. Any other queries please create a new issue.

Kind Regards,

Steve.
